### ISSUE TITLE
push sketch to pcb does not push external/defining geometry edges

### ISSUE THREAD

**Issue by smarq8** [easyw/kicadStepUpMod#109]
As I try to push some sketch to PCB then it does not include any external/defining geometry edges.
The zigzag (polyline) on the left is pushed but defining geometry (pink line) is not.
![screenshot 1641695665](https://user-images.githubusercontent.com/5141045/148666906-0e8284dc-3491-472d-afa1-f238cdc3ce04.png)

**Comment by easyw** [comment]
> The zigzag (polyline) on the left is pushed but defining geometry (pink line) is not.

Hi @smarq8 
this is by design... as kicad requires for a pcb a closed edge, the same my wb is pushing only a closed edge.
If you want to push extra geometries, please push it using a different layer and then move it inside pcbnew.

![push-layers](https://user-images.githubusercontent.com/3032347/148697772-c64f7e29-5654-4af4-a005-2a7f606346c6.png)
