### ISSUE TITLE
import of PCB not possible

### ISSUE THREAD

**Issue by slaesh** [easyw/kicadStepUpMod#120]
I have this problem with an actual PCB and couldn't find the problem.
I just copied it and removed everything and created a dummy PCB... still the same problem?!
![image](https://user-images.githubusercontent.com/55546823/157290617-0d394506-2b36-497c-a3ee-98651e002de0.png)

Is my KiCAD file broken? I am not sure why he is throwing this error

error message complains about edge cuts:
![image](https://user-images.githubusercontent.com/55546823/157290734-3264ac56-687d-426c-a804-5684fbcba531.png)

![image](https://user-images.githubusercontent.com/55546823/157290010-7fd64918-fd42-4ef4-aca3-016f7d274dad.png)

the kicad project (v6)
[inwall-relay-test-edge-cuts.zip](https://github.com/easyw/kicadStepUpMod/files/8208225/inwall-relay-test-edge-cuts.zip)

the resulting sketch
![image](https://user-images.githubusercontent.com/55546823/157290121-2cbe329d-98ad-44f0-b5b6-d14134bd68c6.png)

its fully constrained, tried to move the corners to see which one he might think is "open"
![image](https://user-images.githubusercontent.com/55546823/157290169-faaf7da9-a4bc-4d6a-9ed5-7e4016df6ed6.png)

**Comment by slaesh** [comment]
after pushing the sketch back to kicad, this happened:

![image](https://user-images.githubusercontent.com/55546823/157290975-b1053cbd-3714-4e9b-9dd6-b547d3a4fb38.png)

**Comment by slaesh** [comment]
okay.. somehow the PCB thickness was `0` !? Oo
anyway.. maybe we want to adjust the error message in this case?
or just take a default value of `1.6mm` or so..  and give the user a hint? =)

**Comment by easyw** [comment]
@slaesh 
it seems you are using a latest Nightly Development Builds kicad v7 release...
StepUp ATM is not fully compatible with Nightly Development Builds... the format of the internal code is changing fast and without any announcement...

From the attached file it seems that kicad code is not adjusting the internal value of the PCB thickness 
`(thickness 0)` to the stack, unless you manually export the stack to the board (even if it is instead assumed on 3d viewer)...
StepUp is getting the internal value and not the stack ATM, so that is the error
You may report this to kicad devs at gitlab

> anyway.. maybe we want to adjust the error message in this case?

This is the option to do it and I will try to add a warning message, but I'm not supporting kv7 ATM because of its very fast format changing and random bugs...

**Comment by slaesh** [comment]
guess my version is screwed up. using kicad-version 6 (self-compiled).
but yeah, not a big deal.. just want to save this time searching for others :)
