### ISSUE TITLE
Does not handle recent V5.99 footprints

### ISSUE THREAD

**Issue by MitjaNemec** [easyw/kicadStepUpMod#66]
In V5.99 footprint file format changed slightly [recently, 2020-11-15](https://gitlab.com/kicad/code/kicad/-/commit/3f1a58bd068d20a2008082532996b48d36e261e5). Instead of `module` the keyword is `footprint`.

I've created a footprint with KiCad 5.99.0-7233-g6a28d6af27 and tried to load it with kicad StepUp version 9.7.1.0 (SHA-1:ce399d239d654aeebc49f88cc4fcd3b5559bd1de) on FreeCad OS Version: 0.19.22670. It failed to load.

If I changed the keyword from `footprint` to `module` it loaded without issues.

**Comment by easyw** [comment]
@MitjaNemec 
thanks for fixing this... honestly I don't understand because the k developers needed to change the footprint format, making all the new libraries not back compatible with the 5.1 release.
Anyway it would need to fix the footprint parsing also for loading pcb in FreeCAD for 5.99 pcbnew version.
The ksu pcb s-expr parser is based on @realthunder fcad_pcb   ...  if you would like to have a look at, I'll be happy to merge it too.
Just search for `class KicadPCB(SexpParser):` in kicadStepUptools.py
